### ISSUE TITLE
Debug mode not working outside windows

### ISSUE THREAD

**Issue by Vespion** [aptabase/aptabase-maui#1]
Hi, I am really enjoying aptabase so far; however, I have encountered an issue with the build mode.

When running, the SDK does not set the build mode to debug unless there is a `DebuggableAttribute` present (on an unrelated side note, the need to add this attribute yourself is not documented anywhere I could see? And it wasn't until I checked the source that I found out it was scanning for the attribute).

On Windows builds, this works correctly, and when stepping through, I can see that SystemInfo has IsDebug set to true. However, when switching to Android, this attribute is lost somehow, and the build mode is set to release.
In addition to this, if the attribute does not have `isJITTrackingEnabled` and `isJITOptimizerDisabled` set to false, then the Android app crashes.

I did check how the native Android/Kotlin SDK determines the build mode, but adding `android:debuggable="true"` does not appear to help.

I've not been able to determine if similar issues exist on iOS/Mac (Or Tizen, for that matter) due to not having any of those devices.

Is there a configuration value needed that I missed or is not documented? Or is this behaviour a bug?

**Comment by goenning** [comment]
That’s for the bug report. That seems to align with what someone recently reported via email.

I tried a few different ways of automatically determining if the app is running in debug or release, and this seemed the best one. It worked on Windows and macOS, but I haven’t tried on other OS, which seems like it doesn’t.

Do you happen to know a better way of doing this? The alternative I’m thinking of is having the “IsDebug” being a required parameter on “UseAptabase” because then you can use the “ #if DEBUG” directive. 

But I’d still prefer if the SDK was able to identify this automatically, I just can’t find a way to do it. 

I’m open to suggestions 🙂

**Comment by Vespion** [comment]
My inclination would be to possibly have the SDK check the debuggable attribute in AndroidManifest.xml like the native SDK does? This can be done with something like this:

```csharp
#if ANDROID
    //ApplicationInfo can be null here (apparently) should it consider it a debug build in that case? Since if a release build doesn't have this something is probably wrong?
    var debug = ((Android.App.Application.Context.ApplicationInfo.Flags & Android.Content.PM.ApplicationInfoFlags.Debuggable) != 0);
#endif
```

And allow the InitOptions to override the automatic build mode just as a general useful catch-all. (For example, if you wanted to release the app with android:debuggable="true" which is technically possible just very odd)

This is also less dependent on Runtime reflection, which is useful for AOT, etc.

**Comment by Vespion** [comment]
Perhaps, as well as adding an override option for build mode into the options, there could be an additional option to disable automatic detection entirely.

Which would be useful if the user wanted to take control of the build mode setting entirely.

Plus, this could jump over any reflection code and thus allow the linker to trim it out, which would be great for AOT and make it compatible with [reflection-less AOT](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/reflection-free-mode.md) (Though I will concede that I might be being a bit preemptive here 😅)

**Comment by goenning** [comment]
I was really trying to avoid platform specific code though, because then there's 4~5 other platforms to thing about as well. Oh Microsoft, why do you have to make it so painful to check if it's in Debug mode? 😅

But that's a good point on AOT, removing the reflection is ideal. Do you think forcing the input of IsDebug during the initialisation is a bad idea?

I'm not 100% happy doing that, but it doesn't seem like there's a simpler way of doing it

**Comment by Vespion** [comment]
True. I suppose another way would be to check if a debugger is attached. As far as I'm aware, that's universal compared to attributes that the linker can remove.

I don't think there's any other way to do it without platform-specific code since debug vs release builds are definitely more of a native concern rather than C#.

I'd say it makes sense just to set IsDebug once during initialisation. It seems very rare that you'd ever need to switch between build modes dynamically. And if you do, you can just spawn another client yourself.

**Comment by joshball** [comment]
@goenning , I just ran into this as well. 

First, to fix it locally, 
You are currently using Assembly.GetEntryAssembly(), any reason why? Unfortunately, it is returning null (and therefore you return false). If you used Assembly.GetExecutingAssembly(), it works fine. 

> The [GetEntryAssembly](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=net-8.0) method can return null when a managed assembly has been loaded from an unmanaged application.

But the other issue is that with MAUI, we have to deploy released products to the app store, not debug. So, even while it is under test, it will be set to release. That said, having a debug flag (or make it a suffix of the key?) should really be an option as well, just to override. 

So, it would be nice to just add
`InitOptions: public bool IsDebug {get;set;},`  
save the `InitOptions `in the constructor (or just the `IsDebug `param), 
and then in `SendEvent`, [`systemProps.isDebug = _sysInfo.IsDebug || _initOptions.IsDebug`](https://github.com/aptabase/aptabase-maui/blob/47eda77e8618f123111f74b92a235c5cac18c778/package/AptabaseClient.cs#L120C1-L121C1);

Or you could make the SystemInfo class public, and allow us to set IsDebug ;-)

**Comment by goenning** [comment]
Hi @joshball i 100% agree with letting users override the IsDebug setting, I just didn’t have the time to make the change it.

would you like to contribute with a PR? Is prefer doing it at initialisations rather than on trackEvent

**Comment by joshball** [comment]
Sure thing. I will get a PR soon.

**Comment by joshball** [comment]
Hey @goenning, I submitted the PR, but I have spent my day doing MAUI updates and what was building and running fine yesterday, is no longer doing so. I will try later this week and let you know (or feel free to pull and test yourself).
Thanks.

**Comment by ckmall** [comment]
Hey all, just chiming--I am really 🤩LOVING🤩 Aptabase for usage reporting for an iOS buils, but facing this frustrating issue for the Android build where the debug usage is being reported under release mode. I would be OK with the solution of setting the debug mode myself. I am happy to test it out if it were available.

**Comment by cristipufu** [comment]
Hi guys, we released a new version of the sdk https://www.nuget.org/packages/Aptabase.Maui/0.0.9. Please try it out and let me know how it goes, thanks!
